Tickers:
  - AAPL
  - MSFT
  - RUN
  - SSL
  - DAR
  - BHC
  - BG
  - APGE
  - ZIM
  - VEON
  - ACHR
  - VFC
  - NEGG
  - GEO
  - SATS
  - CVNA
  - MTDR
  - FSLR
  - MP
  - MEOH
  - ONON
  - NBIS
  - ACVA
  - MPWR
IndicatorParameters:
  SMAWindow: 5
  EMAWindow: 5
  VolatilityWindow: 5
  MACDShort: 12
  MACDLong: 26
  MACDSignal: 9
  BBWindow: 20
  BBStd: 2
  ADIWindow: 14
MomentumLookbacks:
  - 5
  - 10
  - 20
  - 30
  - 40
  - 50
LookbackWeights:
  Lookback_5: 1.0
  Lookback_10: 1.0
  Lookback_20: 1.0
  Lookback_30: 1.0
  Lookback_40: 1.0
  Lookback_50: 1.0
IndicatorWeights:
  SMA: 1.0
  EMA: 1.0
  RSI: 1.0
  Volatility: 1.0
  MACD: 1.0
  BB: 1.0
  ADI: 1.0
MomentumWeight: 1.0
AllocationMethod: volatility
CsvPath: portfolio.csv
JsonPath: portfolio.json
RebalanceIntervalMonths: 3
TrainingEndDate: '2023-12-31'
InitialCash: 50000
